/**
 * Garden Caring : Services
 * This is the Transfarmers backend api documentation
 *
 * OpenAPI spec version: 0.1
 * Contact: mathias.couste@garden-sharing.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
    Http,
    Headers,
    RequestOptionsArgs,
    Response,
    URLSearchParams
} from "@angular/http";
import {
    Injectable,
    Optional
} from "@angular/core";
import {Observable} from "rxjs/Observable";
import {Plot} from "../../models/index";
import "rxjs/Rx";

/* tslint:disable:no-unused-variable member-ordering */

'use strict';

@Injectable()
export class LandApi {
    protected basePath            = 'http://gardencaring-services.eu-gb.mybluemix.net/rest';
    public defaultHeaders:Headers = new Headers();

    constructor(protected http:Http, @Optional() basePath:string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * Create a plot.
     *
     * @param body Plot to create
     */
    public createPlot(body:Plot, extraHttpRequestParams?:any):Observable<Plot> {
        const path = this.basePath + '/land/plot';

        let queryParameters = new URLSearchParams();
        let headerParams    = this.defaultHeaders;
        // verify required parameter 'body' is set
        if (!body) {
            throw new Error('Missing required parameter body when calling createPlot');
        }
        let requestOptions:RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body                   = JSON.stringify(body);

        return this.http.request(path, requestOptions)
            .map((response:Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Find plot using an id.
     *
     * @param plotid plotid
     */
    public findPlotById(plotid:string, extraHttpRequestParams?:any):Observable<Plot> {
        const path = this.basePath + '/land/plot/{plotid}'
                .replace('{' + 'plotid' + '}', String(plotid));

        let queryParameters = new URLSearchParams();
        let headerParams    = this.defaultHeaders;
        // verify required parameter 'plotid' is set
        if (!plotid) {
            throw new Error('Missing required parameter plotid when calling findPlotById');
        }
        let requestOptions:RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response:Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * List plots
     *
     * @param tenantid tenantid
     */
    public findPlots(tenantid?:string, extraHttpRequestParams?:any):Observable<Array<Plot>> {
        const path = this.basePath + '/land/plot';

        let queryParameters = new URLSearchParams();
        let headerParams    = this.defaultHeaders;
        if (tenantid !== undefined) {
            queryParameters.set('tenantid', tenantid);
        }

        let requestOptions:RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response:Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Update a plot.
     *
     * @param body Plot to update
     */
    public updatePlot(body:Plot, extraHttpRequestParams?:any):Observable<Plot> {
        const path = this.basePath + '/land/plot';

        let queryParameters = new URLSearchParams();
        let headerParams    = this.defaultHeaders;
        // verify required parameter 'body' is set
        if (!body) {
            throw new Error('Missing required parameter body when calling updatePlot');
        }
        let requestOptions:RequestOptionsArgs = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body                   = JSON.stringify(body);

        return this.http.request(path, requestOptions)
            .map((response:Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
